pathfinder/charsheet/urls.py
from django.urls import path

from . import views

app_name = 'charsheet'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:character_id>/', views.sheet, name='sheet'),
    path('<int:character_id>/detail', views.detail, name='detail'),
    path('<int:character_id>/add_roll', views.add_roll, name='add_roll'),
]

webserver/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('pathfinder/', include('webserver.pathfinder.urls')),
    path('polls/', include('webserver.polls.urls')),
    path('admin/', admin.site.urls),
]

pathfinder/charsheet/models.py
from logging import getLogger

from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db.models import (BooleanField, CASCADE, CharField, Count, ForeignKey, ManyToManyField, Model,
                              PositiveIntegerField, SET_NULL)

from backend.ability_scores import get_modifier, get_carrying_capacity
from charsheet.bonuses import get_total_bonus
from charsheet.constants import AlignmentGoodAxis, AlignmentLawAxis, Gender, Size
from util.enums import enum_to_choices

logger = getLogger(__name__)


class Skill(Model):
    name = CharField(max_length=32, unique=True)
    key_ability = CharField(max_length=16)
    trained_only = BooleanField(default=False)

    def armor_check_penalty(self):
        return self.key_ability == 'strength' or self.key_ability == 'dexterity'

    def __str__(self) -> str:
        return f'{self.name}'


class CharacterClass(Model):
    name = CharField(max_length=32, null=False, blank=False, unique=True)
    # In base classes these tend to be alignment restrictions, but prestige classes are also possible
    requirements = CharField(max_length=256, null=True, blank=True)  # May change field type
    is_prestige_class = BooleanField(default=False)  # Needed because saves start out slightly different
    hit_die = PositiveIntegerField()
    class_skills = ManyToManyField(Skill)
    starting_wealth = CharField(max_length=32, null=True, blank=True)
    skill_ranks = PositiveIntegerField()
    base_attack_progression = CharField(max_length=32)  # TODO limit option to half, 3/4 and full
    good_fortitude_progression = BooleanField()
    good_reflex_progression = BooleanField()
    good_will_progression = BooleanField()
    # TODO add abilities and spells
    # TODO add proficiencies

    class Meta:
        verbose_name_plural = 'CharacterClasses'

    def __str__(self) -> str:
        return f'{self.name}'


class Race(Model):
    name = CharField(max_length=32, null=False, blank=False, unique=True)
    # ability scores
    # type(s)
    size = CharField(max_length=16, default=Size.MEDIUM.name, choices=enum_to_choices(Size))
    base_speed = PositiveIntegerField(help_text='expressed in feet')
    # languages
    # language options

    fly_speed = PositiveIntegerField(default=0, help_text='expressed in feet')
    # TODO make enum for these options
    fly_maneuverability = CharField(max_length=32, default='')  # Needs only be set if fly speed is
    swim_speed = PositiveIntegerField(default=0, help_text='expressed in feet')
    climb_speed = PositiveIntegerField(default=0, help_text='expressed in feet')
    burrow_speed = PositiveIntegerField(default=0, help_text='expressed in feet')

    # racial traits

    def __str__(self) -> str:
        return f'{self.name}'


class Language(Model):
    name = CharField(max_length=32, null=False, blank=False, unique=True)
    secret = BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.name}'


class Character(Model):
    # I want every field of this Model to have a default so it can be left empty during construction

    # Description fields
    name = CharField(max_length=128, blank=True, default='')
    alignment_law_axis = CharField(max_length=8, default=AlignmentLawAxis.TRUE.name,
                                   choices=enum_to_choices(AlignmentLawAxis))
    alignment_good_axis = CharField(max_length=8, default=AlignmentGoodAxis.NEUTRAL.name,
                                    choices=enum_to_choices(AlignmentGoodAxis))
    player = CharField(max_length=128, blank=True, default='')
    deity = CharField(max_length=128, blank=True, default='')
    homeland = CharField(max_length=128, blank=True, default='')
    race = ForeignKey(Race, null=True, default=None, on_delete=SET_NULL)
    size = CharField(max_length=16, default=Size.MEDIUM.name,
                     choices=enum_to_choices(Size))
    gender = CharField(max_length=8, default=Gender.MALE.name,
                       choices=enum_to_choices(Gender))
    age = PositiveIntegerField(default=0)
    height = PositiveIntegerField(default=0, help_text='expressed in inches')
    weight = PositiveIntegerField(default=0, help_text='expressed in pounds')
    hair = CharField(max_length=32, blank=True, default='')
    eyes = CharField(max_length=32, blank=True, default='')

    experience = PositiveIntegerField(default=0)  # TODO change so it can be tracked per session
    languages = ManyToManyField(Language, blank=True)

    def alignment_readable(self):
        return f'{AlignmentLawAxis[self.alignment_law_axis].value} {AlignmentGoodAxis[self.alignment_good_axis].value}'

    def size_readable(self):
        return Size[self.size].value

    def gender_readable(self):
        return Gender[self.gender].value

    def height_readable(self):
        return f'{self.height // 12}\' {self.height % 12}"'

    def weight_readable(self):
        return f'{self.weight} lbs.'

    base_strength = PositiveIntegerField(default=10)
    base_dexterity = PositiveIntegerField(default=10)
    base_constitution = PositiveIntegerField(default=10)
    base_intelligence = PositiveIntegerField(default=10)
    base_wisdom = PositiveIntegerField(default=10)
    base_charisma = PositiveIntegerField(default=10)

    copper = PositiveIntegerField(default=0)
    silver = PositiveIntegerField(default=0)
    gold = PositiveIntegerField(default=0)
    platinum = PositiveIntegerField(default=0)

    def strength(self):
        return self.base_strength + get_total_bonus(self, 'strength')

    def strength_modifier(self):
        return get_modifier(self.strength())

    def dexterity(self):
        return self.base_dexterity + get_total_bonus(self, 'dexterity')

    def dexterity_modifier(self):
        return get_modifier(self.dexterity())

    def constitution(self):
        return self.base_constitution + get_total_bonus(self, 'constitution')

    def constitution_modifier(self):
        return get_modifier(self.constitution())

    def intelligence(self):
        return self.base_intelligence + get_total_bonus(self, 'intelligence')

    def intelligence_modifier(self):
        return get_modifier(self.intelligence())

    def wisdom(self):
        return self.base_wisdom + get_total_bonus(self, 'wisdom')

    def wisdom_modifier(self):
        return get_modifier(self.wisdom())

    def charisma(self):
        return self.base_charisma + get_total_bonus(self, 'charisma')

    def charisma_modifier(self):
        return get_modifier(self.charisma())

#    def class_and_level(self):
#        levels = self.levels.values('character_class__name').annotate(Count("id")).order_by()
#        output = ', '.join(f"{level['character_class__name']} {level['id__count']}" for level in levels)
#        return f'{self.level()}: {output}'

    def class_and_level(self):
        # TODO this works but is hideous compared to the code above (which only shows the classes in a different
        # order than I would like
        levels = self.levels.values('character_class__name').annotate(Count("id")).order_by()
        levels = {level['character_class__name']: level['id__count'] for level in levels}
        o = self.levels.values('character_class__name').order_by('character_level')
        res = []
        for l in o:
            if l['character_class__name'] in levels:
                res.append(f"{l['character_class__name']} {levels[l['character_class__name']]}")
                del levels[l['character_class__name']]
        output = ', '.join(res)
        return f'{self.level()}: {output}'

    def level(self):
        return self.levels.count()
    
    def hit_dice(self):
        return self.level()

    def get_starting_hit_points(self):
        # TODO error handling, but I want to handle the specific error
        return self.levels.filter(character_level=1).get().character_class.hit_die

    def hit_points(self):
        return self.get_starting_hit_points() \
               + sum(roll.result for roll in self.roll_set.all()) \
               + get_modifier(self.constitution()) * self.level() \
               + get_total_bonus(self, 'hit points')

    def damage_resistance(self):
        return 0 + get_total_bonus(self, 'damage resistance')

    def initiative(self):
        return get_modifier(self.dexterity()) + get_total_bonus(self, 'initiative')

    def safe_race(self):
        return self.race or Race.objects.get(name='Human')

    def base_speed(self):
        return self.safe_race().base_speed + get_total_bonus(self, 'base speed')

    def speed_with_armor(self):
        return self.base_speed()  # TODO check gear for armor

    def fly_speed(self):
        speed = self.get_best_speed('fly')
        return max(self.safe_race().fly_speed, speed) + get_total_bonus(self, 'fly speed')

    def fly_maneuverability(self):
        try:
            # TODO will not work with more than 1 fly speed present
            return self.speed_set.filter(type='fly').get().maneuverability
        except:
            return self.safe_race().fly_maneuverability

    def swim_speed(self):
        speed = self.get_best_speed('swim')
        return max(self.safe_race().swim_speed, speed) + get_total_bonus(self, 'swim speed')

    def climb_speed(self):
        speed = self.get_best_speed('climb')
        return max(self.safe_race().climb_speed, speed) + get_total_bonus(self, 'climb speed')

    def burrow_speed(self):
        speed = self.get_best_speed('burrow')
        return max(self.safe_race().burrow_speed, speed) + get_total_bonus(self, 'burrow speed')

    def get_best_speed(self, type):
        # TODO maneuverability
        try:
            return max(s.speed for s in self.speed_set.filter(type=type).all())
        except ValueError:
            return 0


    # TODO refactor the 3 AC calculations into a coherent whole
    def armor_class(self):
        try:

pathfinder/charsheet/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse

from charsheet.models import Character, Roll, Skill
from webserver.util.view_decorators import template_view


@template_view('charsheet/index.html')
def index():
    # For now, shows everything. Should the amount become too large, this should change
    characters = Character.objects.order_by('name')
    return {'characters': characters}


@template_view('charsheet/sheet.html')
def sheet(character_id: int) -> HttpResponse:
    character = get_object_or_404(Character, pk=character_id)
    skills = Skill.objects.all()
    return {'character': character, 'skills': skills}


@template_view('charsheet/detail.html')
def detail(character_id: int) -> HttpResponse:
    character = get_object_or_404(Character, pk=character_id)
    skills = Skill.objects.all()
    return {'character': character, 'skills': skills}


def add_roll(request: HttpRequest, character_id: int) -> HttpResponse:
    reason = request.POST['reason']
    die_size = request.POST['die_size']
    result = request.POST['result']

    assert die_size <= result  # This can be done front-end as well (Django form validation)

    roll = Roll(die_size=die_size, result=result, reason=reason, character_id=character_id)
    roll.save()

    return HttpResponseRedirect(reverse('charsheet:detail', args=(character_id,)))

# Not sure yet of other views, apply enlarge, apply spell,...

pathfinder/charsheet/templates/charsheet/detail.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<h1>{{ character.name }}</h1>
STR {{ character.base_strength }}<br>
CON {{ character.base_constitution }}<br>
DEX {{ character.base_dexterity }}<br>
INT {{ character.base_intelligence }}<br>
WIS {{ character.base_wisdom }}<br>
CHA {{ character.base_charisma }}<br>
<ul>
{% for roll in character.roll_set.all %}
    <li>{{ roll.result }}/{{ roll.die_size }}: {{ roll.reason }}</li>
{% endfor %}
</ul>

<form action="{% url 'charsheet:add_roll' character.id %}" method="post">
{% csrf_token %}
    reason: <input type="text" name="reason" id="reason"/>
    die size: <input type="text" name="die_size" id="die_size"/>
    result: <input type="text" name="result" id="result"/>
<input type="submit" value="Add roll" />
</form>

pathfinder/charsheet/templates/charsheet/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'charsheet/style.css' %}" />

<h3>Characters</h3>
{% if characters %}
    <ul>
    {% for character in characters %}
        <li><a href="{% url 'charsheet:detail' character.id %}">{{ character.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No characters are available.</p>
{% endif %}

pathfinder/charsheet/templates/charsheet/sheet.html
{% load static %}

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'charsheet/pathfinder.css' %}">
        <link rel="shortcut icon" href="{% static 'charsheet/images/favicon.ico' %}" type="image/x-icon">
    </head>
    <body>
        <table>
            <tr>
                <td style="vertical-align: top">
                    <img src="{% static 'charsheet/images/PathfinderRPGLogo_500.jpeg' %}" style="width: 300px;"/>
                    <div style="text-align: center; font-size: 2em;">Character Sheet</div>
                </td>
                <td style="vertical-align: top">
                    {% include "charsheet/sheet_parts/description.html" %}
                </td>
            </tr>
        </table>
        <table>
            <tr>
                <td style="vertical-align: top">
                    <table>
                        <tr>
                            <td style="vertical-align: top">
                                {% include "charsheet/sheet_parts/abilities.html" %}
                            </td>
                            <td style="vertical-align: top">
                                {% include "charsheet/sheet_parts/hp.html" %}
                                {% include "charsheet/sheet_parts/initiative.html" %}
                            </td>
                        </tr>
                    </table>
                    {% include "charsheet/sheet_parts/AC.html" %}
                    {% include "charsheet/sheet_parts/saves.html" %}
                    {% include "charsheet/sheet_parts/attack.html" %}
                    {% include "charsheet/sheet_parts/weapons.html" %}
                </td>
                <td style="vertical-align: top">
                    {% include "charsheet/sheet_parts/speed.html" %}
                    {% include "charsheet/sheet_parts/skills.html" %}
                    {% include "charsheet/sheet_parts/languages.html" %}
                </td>
            </tr>
        </table>
        <!-- TODO find a way to add a pagebreak in printing if possible -->
        <hr/>
        <table>
            <tr>
                <td style="vertical-align: top">
                    {% include "charsheet/sheet_parts/AC_items.html" %}
                    <table>
                        <tr>
                            <td style="vertical-align: top">
                                {% include "charsheet/sheet_parts/gear.html" %}
                                {% include "charsheet/sheet_parts/load.html" %}
                                {% include "charsheet/sheet_parts/money.html" %}
                            </td>
                            <td style="vertical-align: top">
                                {% include "charsheet/sheet_parts/feats.html" %}
                                {% include "charsheet/sheet_parts/special_abilities.html" %}
                                {% include "charsheet/sheet_parts/experience.html" %}
                            </td>
                        </tr>
                    </table>
                </td>
                <td style="vertical-align: top">
                    {% include "charsheet/sheet_parts/spells.html" %}
                    {% include "charsheet/sheet_parts/spells_known.html" %}
                </td>
            </tr>
        </table>
    </body>
</html>