webserver/polls/urls.py
from django.urls import path

from webserver.polls.views import detail, index, results

app_name = 'polls'
urlpatterns = [
    path('', index, name='index'),
    path('<int:question_id>/', detail, name='detail'),
    path('<int:question_id>/results/', results, name='results'),
]

webserver/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('pathfinder/', include('webserver.pathfinder.urls')),
    path('polls/', include('webserver.polls.urls')),
    path('admin/', admin.site.urls),
]

webserver/polls/models.py
from datetime import timedelta

from django.db.models import CASCADE, CharField, DateTimeField, ForeignKey, IntegerField, Model
from django.utils.timezone import now


class Question(Model):
    text = CharField(max_length=200, default=None, blank=False, null=False)
    publication_time = DateTimeField(default=now, blank=False, null=False)

    def was_published_recently(self) -> bool:
        """ Returns whether the Question was published in the last day (and not in the future) """
        current_time = now()
        return current_time - timedelta(days=1) <= self.publication_time <= current_time
    was_published_recently.admin_order_field = 'publication_time'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self) -> str:
        return str(self.text)


class Choice(Model):
    question = ForeignKey(Question, on_delete=CASCADE, blank=False, null=False)
    text = CharField(max_length=200, default=None, blank=False, null=False)
    votes = IntegerField(default=0, blank=True, null=False)

    def __str__(self) -> str:
        return str(self.text)

webserver/polls/views.py
from typing import Any, Dict

from django.db.models import F
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.http import require_GET, require_http_methods

from webserver.polls.models import Choice, Question
from webserver.util.view_decorators import template_view

INDEX_SIZE = 5


@require_GET
@template_view('polls/index.html')
def index() -> Dict[str, Any]:
    questions = Question.objects.filter(publication_time__lte=timezone.now()).order_by('-publication_time')[:INDEX_SIZE]

    return {'questions': questions}


@require_http_methods(["GET", "POST"])
def detail(request: HttpRequest, *, question_id: int) -> HttpResponse:
    question = get_object_or_404(Question, publication_time__lte=timezone.now(), pk=question_id)
    context = {}

    if request.method == 'POST':
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
            selected_choice.votes = F('votes') + 1
            selected_choice.save()

            return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))
        except KeyError:
            context['error_message'] = "You didn't select a choice."
        except Choice.DoesNotExist:
            context['error_message'] = 'Choice not found.'

    context.update({'question': question})
    return render(request, 'polls/detail.html', context)


@require_GET
@template_view('polls/results.html')
def results(*, question_id: int) -> Dict[str, Any]:
    question = get_object_or_404(Question, publication_time__lte=timezone.now(), pk=question_id)

    return {'question': question}

webserver/polls/templates/polls/base.html
{% load static %}

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    </head>

    <body>
        {% block content %}{% endblock %}
        <a href="{% url 'polls:index' %}">Home</a>
    </body>
</html>

webserver/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}
    <h1>{{ question.text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:detail' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.text }}</label><br>
        {% endfor %}
        <br>
        <input type="submit" value="Vote">
    </form>
{% endblock %}

webserver/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}
    {% if questions %}
        <ul>
        {% for question in questions %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

webserver/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}